### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by kareemelzeftawy** [goruck/edge-tpu-servers#2]
I installed the whole libraries and i generated the (encodings.pickle), I'm using Adrian [dataset](https://www.pyimagesearch.com/2018/06/18/face-recognition-with-opencv-python-and-deep-learning/)

I got this error when I ran train.py

`Encoding labels...

 Finding best svm estimator...
Fitting 5 folds for each of 42 candidates, totalling 210 fits
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    best_svm = find_best_svm_estimator(X_train, y_train, skf.split(X_train, y_train))
  File "train.py", line 64, in find_best_svm_estimator
    grid_search.fit(X, y)
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/model_selection/_search.py", li                                                                            ne 722, in fit
    self._run_search(evaluate_candidates)
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/model_selection/_search.py", li                                                                            ne 1191, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/model_selection/_search.py", li                                                                            ne 711, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py",                                                                             line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py",                                                                             line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py",                                                                             line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_back                                                                            ends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_back                                                                            ends.py", line 549, in __init__
    self.results = batch()
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py",                                                                             line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py",                                                                             line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/model_selection/_validation.py"                                                                            , line 528, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/svm/base.py", line 149, in fit
    accept_large_sparse=False)
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/utils/validation.py", line 756,                                                                             in check_X_y
    estimator=estimator)
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/utils/validation.py", line 573,                                                                             in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/fruits/tpu/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56,                                                                             in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
`

my scikit-learn library version: 0.20.3
can anyone help me

**Comment by goruck** [comment]
@Karem-Elzftawy it looks like the encodings may contain invalid entries.

1. Did you use [encode_faces.py](https://github.com/goruck/edge-tpu-servers/blob/master/encode_faces.py) to generate the encodings? If not how did you do it?

2. Assuming you used [encode_faces.py](https://github.com/goruck/edge-tpu-servers/blob/master/encode_faces.py) do you get ```'*** no face found! ***'``` warnings? If so that means faces were not found in the images you provided and so no encodings were generated for that face. Hopefully at least some faces were found in the training data you provided. 

3. In [train.py](https://github.com/goruck/edge-tpu-servers/blob/master/train.py), [uncomment this line](https://github.com/goruck/edge-tpu-servers/blob/master/train.py#L108) and rerun it. Take a look at the train and test data and see if they make sense. You can paste them to this issue and I can take a look too.

**Comment by goruck** [comment]
Closing due to inactivity.
